# default config
baseurl = "https://urbanlivingjournal.com"
languageCode = "en-us"
title = "Urban Living Journal"
theme = "parsa"
summaryLength = "10"
paginate = 6
# google analytics
googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
# note: add it back later
# [[menu.main]]
# name = "Homepage"
# url = "homepage/home-1"
# weight = 1
# hasChildren = true

  # [[menu.main]]
  # parent = "Homepage"
  # name = "Homepage 1"
  # url = "homepage/home-1"

  # [[menu.main]]
  # parent = "Homepage"
  # name = "Homepage 2"
  # url = "homepage/home-2"

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact"
weight = 3

# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "Urban Living Journal"
author_image = "images/banner-img.png"
bio = "Iâ€™m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
# Contact info
# mobile = "+00000000"
email = "urbanlivingjournal@gmail.com"
address = "Pacific Northwest"
# Contact Form Action
contact_form_action = "#"
# copyright
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"

# Instagram feed
[params.instafeed]
enable = false
access_token = ""

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/UrbanLivingJou1"

# [[params.social]]
# icon = "ti-linkedin"
# link = "#"

# [[params.social]]
# icon = "ti-github"
# link = "#"